import type { Metadata } from "next";
import { HeadTitle } from "@/components/modalSlider/head-title/HeadTitle";

import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative h-screen">
      <HeadTitle />
        {children}
        </div>
      </body>
    </html>
  );
}
